### ISSUE TITLE
When opening Signal via Flatpak the following error message appears:

### ISSUE THREAD

**Issue by serial02** [flathub/org.signal.Signal#431] opened 2023-04-07 13:24 UTC
Hello Signal team

 When opening Signal via Flatpak, it opens and works normally, however, the following error messages appear in the terminal:

```
flatpak run org.signal.Signal
Debug: Will run signal with the following arguments: 
Debug: Additionally, user gave: 
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /app/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME localhost.localdomain
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/edson/.var/app/org.signal.Signal/config/Signal
config/start: Did not find user config file (or it was empty), cache is now empty object
config/start: Did not find ephemeral config file (or it was empty), cache is now empty object
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 10:10:53.935: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:10:54.020: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:10:54.056: Failed to load module "canberra-gtk-module"
[2:0407/101054.111681:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Arquivo ou diretório inexistente
[2:0407/101054.111860:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Arquivo ou diretório inexistente
[2:0407/101054.453507:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Arquivo ou diretório inexistente
[2:0407/101054.453615:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Arquivo ou diretório inexistente
[2:0407/101054.453695:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Arquivo ou diretório inexistente
(node:87) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `exe --trace-deprecation ...` to show where the warning was created)


```

Reporting only for verification purposes and possible correction for app improvements.

![Captura de tela de 2023-04-07 10-12-37](https://user-images.githubusercontent.com/32621790/230615788-2fd41818-d094-400f-af66-69188713dd61.png)

System data:

![Capturar_select-area_20230407102217](https://user-images.githubusercontent.com/32621790/230616278-9acebaaa-6690-4e3d-9562-763def65b25f.png)

**Comment by serial02** [comment] 2023-04-08 13:36
just for the record

 See that in fedora 37 the same error message occurs when opening the application.

```
flatpak update
Procurando por atualizações…

Nada para fazer.
[edson@fedora ~]$ flatpak install flathub org.signal.Signal
Procurando por correspondências…
Runtime exigido para org.signal.Signal/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/22.08) localizado no remoto flathub
Você deseja instalá-lo? [Y/n]: y

Permissões de org.signal.Signal:
    ipc            network                pulseaudio            wayland                 x11
    devices        file access [1]        dbus access [2]       bus ownership [3]

    [1] xdg-desktop, xdg-documents, xdg-download, xdg-music, xdg-pictures, xdg-public-share, xdg-videos
    [2] com.canonical.AppMenu.Registrar, com.canonical.indicator.application, org.ayatana.indicator.application,
        org.freedesktop.Notifications, org.freedesktop.portal.Background, org.freedesktop.portal.Fcitx,
        org.gnome.Mutter.IdleMonitor, org.kde.StatusNotifierWatcher
    [3] org.kde.*


        ID                                       Ramo            Op          Remoto          Baixar
 1. [✓] org.freedesktop.Platform.Locale          22.08           i           flathub         144,6 kB / 333,2 MB
 2. [✓] org.freedesktop.Platform                 22.08           i           flathub          95,4 MB / 214,5 MB
 3. [✓] org.signal.Signal                        stable          i           flathub         151,2 MB / 149,7 MB

Instalação concluída.
[edson@fedora ~]$ flatpak run org.signal.Signal
Debug: Will run signal with the following arguments: 
Debug: Additionally, user gave: 
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /app/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/edson/.var/app/org.signal.Signal/config/Signal
config/start: Did not find user config file (or it was empty), cache is now empty object
config/start: Did not find ephemeral config file (or it was empty), cache is now empty object
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 10:19:50.655: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:19:50.655: Failed to load module "pk-gtk-module"
Gtk-Message: 10:19:50.797: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:19:50.798: Failed to load module "pk-gtk-module"
[2:0408/101950.873792:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Arquivo ou diretório inexistente
[2:0408/101950.874007:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Arquivo ou diretório inexistente
[2:0408/101952.349845:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Arquivo ou diretório inexistente
[2:0408/101952.349959:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Arquivo ou diretório inexistente
[2:0408/101952.350062:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Arquivo ou diretório inexistente
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
(node:80) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `exe --trace-deprecation ...` to show where the warning was created)
```

![Captura de tela de 2023-04-08 10-34-48](https://user-images.githubusercontent.com/32621790/230724056-9e0bd5d1-0fe5-4166-837e-13e227852da5.png)

**Comment by Maltimore** [comment] 2023-04-26 12:31
It prints similar warnings for me, but I have been using signal without issue for years, so I would not consider this a bug, especially not of the flatpak version.

**Comment by al12gamer** [comment] 2023-05-30 17:28
Don't know if this is a similar issue but I keep experiencing disconnects on mine it seems. I only see one failed to connect error here.
```
Debug: Will run signal with the following arguments: 
Debug: Additionally, user gave: 
[2:0530/112512.565162:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /app/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/s31bz/.var/app/org.signal.Signal/config/Signal
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
```
and here's a neofetch
![Screenshot_20230530_112629](https://github.com/flathub/org.signal.Signal/assets/10056498/476ddedb-c1d9-4181-a3d0-1fffd15e8213)

**Comment by razzeee** [comment] 2023-06-18 14:05
Seems to be a duplicate of https://github.com/flathub/org.signal.Signal/issues/280

**Comment by al12gamer** [comment] 2023-06-19 20:03
Ignore my post, as my signal flatpak is fixed.

**Closed** 2023-10-02 08:52 UTC
