### ISSUE TITLE
How to add another arch the Signal flatpak?

### ISSUE THREAD

**Issue by develroo** [flathub/org.signal.Signal#46] opened 2018-09-19 15:48 UTC
I am running Debian  on a Gemini PDA and would like to install Signal Desktop for it. The pre-built Debian packages are not available for the arm64 architecture which the Gemini is running. 

Flatpaks would seem the easiest way to install Signal Desktop, so how do I go about either building the flatpak myself for that arch or making a formal request to have this arch added to the flathub repo?

Thanks.

**Comment by TingPing** [comment] 2018-09-19 16:10
You will have to figure out how to build it. The source is here: https://github.com/signalapp/Signal-Desktop

A few other apps built similar to it exist: https://github.com/search?q=org%3Aflathub+yarn&type=Code

**Comment by ExTechOp** [comment] 2019-08-05 19:33
@develroo Have you been successful since, since I'm kinda also looking for the arm64 version to run under Chrome OS?

**Comment by develroo** [comment] 2019-08-06 10:57
Not as of now. Hit a few dependency issues and haven't had the time to look into it. Maybe after the summer I can find time.

**Comment by ExTechOp** [comment] 2019-12-18 05:12
Apparently you have not been successful with this project?

**Comment by ExTechOp** [comment] 2020-01-18 09:24
It would be really nice to get support also for the arm64 (aarch64) architecture.

**Comment by SebDanielsson** [comment] 2022-01-18 13:17
Should be possible now since Signal Desktop for Mac is now Apple Silicon compatible.

**Comment by TingPing** [comment] 2022-01-18 13:24
It was never a question of can it run, obviously its just an Electron app.

The problem is they don't distribute binaries for arm64 Linux and building it, like most Electron apps, is a PITA.

**Comment by SebDanielsson** [comment] 2022-01-18 13:38
This might be the wrong place to ask but is there a guide on how to build it locally on an arm64 Linux distro?

**Comment by janvlug** [comment] 2022-01-18 17:27
> is there a guide on how to build it locally on an arm64 Linux distro?

Maybe this is useful: https://gitlab.com/undef1/signal-desktop-builder

**Comment by bermeitinger-b** [comment] 2022-01-19 09:36
We need to build from source to support other arches.

Closed in favor of #208

**Closed by bermeitinger-b** 2022-01-19 09:36 UTC
