### ISSUE TITLE
Signal Desktop Crashing When Clicking Notification

### ISSUE THREAD

**Issue by sbarnard86** [flathub/org.signal.Signal#527] opened 2023-10-01 23:06 UTC
Just updated to newest version of Signal Desktop and it crashes when clicking on a notification of a new message. 

[debuglog_SignalDesktop.txt](https://github.com/flathub/org.signal.Signal/files/12778454/debuglog_SignalDesktop.txt)

**Comment by bermeitinger-b** [comment] 2023-10-02 08:47
Duplicate of #521

**Closed by bermeitinger-b** 2023-10-02 08:47 UTC
