### ISSUE TITLE
Unable to open Preferences

### ISSUE THREAD

**Issue by kurobeats** [flathub/org.signal.Signal#84] opened 2019-06-30 07:31 UTC
The Preferences opens blank:
![Screenshot from 2019-06-30 15-29-17](https://user-images.githubusercontent.com/4091936/60393716-1eea4480-9b4c-11e9-898c-5db86e11d9a7.png)

Console message:

```
{
    "name": "log",
    "hostname": "hostname",
    "pid": 2,
    "level": 50,
    "msg": "Top-level unhandled promise rejection: RangeError: Unsupported time zone specified undefined",
    "time": "2019-06-30T07:29:38.521Z",
    "v": 0
}
```

**Comment by bermeitinger-b** [comment] 2019-07-01 08:54
I can't reproduce. Which "obscure" timezone do you have specified?

**Comment by kurobeats** [comment] 2019-07-01 09:42
What makes a timezone obscure? The moon? Indie music?

Nothing set manually, outside of the OS which is UTC.

**Comment by bermeitinger-b** [comment] 2019-07-01 10:10
I'm sorry for the direct question. I can reproduce this when setting `TZ` to an unknown value (e.g. moon). 
You can enforce the timezone by setting the environment variable TZ before running:
`TZ=UTC flatpak run org.signal.Signal`

I'll close this then, it seems like an upstream issue.

**Closed by bermeitinger-b** 2019-07-01 10:10 UTC

**Comment by kurobeats** [comment] 2019-07-01 10:23
> I'm sorry for the direct question
It's fine, it just made me laugh.

> I'll close this then, it seems like an upstream issue.
I'm starting to think it is, but a flatpak related issue. The discord app is encountering a similar issue: https://github.com/flathub/com.discordapp.Discord/issues/53#issuecomment-496020265
